config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root 'items#index'
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
	mount_uploader :logo, LogoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :website, :city, :address, :category, :description, :logo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<table id="businesses">
  <thead>
    <tr>
      <th>Business</th>
      <th></th>
      <th>Area</th>
      <th>Product or Service</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td class="business-logo"><%= image_tag(item.logo_url, :class => 'business-logo-image', :alt => item.name) if item.logo.present? %>
        </td>
        <td class="business-name">
          <a href="http://<%= item.website %>">
              <%= item.name %>
          </a>
        </td>
        <td class="business-area"><%= item.city %>
          <p class="business-address"><%= item.address %></p>
        </td>
        <td class="business-type"><%= item.category %>
          <p class="business-description"><%= item.description %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @item.website %>
</p>

<p>
  <strong>City:</strong>
  <%= @item.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @item.address %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag(@item.logo_url, :width => 100) if @item.logo.present? %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Made with Love in Ohio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//use.typekit.net/jru4nmp.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="site-header">
  <h1>Made with Love in Ohio</h1>
  <p>Exceptionally beautiful projects made with love in the heart of the Midwest.</p>
</header>

  <%= yield %>

<footer class="site-footer">
  <p>Made with love in Ohio. &hearts;
  	<svg version="1.1"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
	 x="0px" y="0px" viewBox="0 0 50.8 49.1" enable-background="new 0 0 50.8 49.1"
	 xml:space="preserve" class="ohio-shape">
	<g>
		<path d="M50.8,1.6c0-1.4,0-2.4-1.4-1c-3.4,3-6.6,1-9.9,4.3c-1,1.1-1.8,0.4-3.3,0.9c-1.5,0.4-3.2,2.1-4.6,2.7
			c-2.5,1.2-4.5,1.3-6.1-1.3c-0.3-0.4-1.1-0.5-1.7-0.7c-0.6,1.9-1.4,0.6-2.2,0.2c-2-1-6-4.8-8-4.8c-2.9,0-7.8,0-13.6,0
			c0,7.2,0,13.5,0,34.7c0,0.6,5.3,5.6,6.1,5.7c2.4,0.3,4.1,2.6,5.7,4.5c0.1,0.1,1.4,0.5,1.5,0.5c1.4-2,4.1,0.4,5,0.1
			c1.1-0.3,4.7-1.6,5-1.3c1.4,1.4,3.4,1.1,4.6,2.7c1.4,1.9,4.1-4.6,5.3-6.4c0.2-0.2,4-1,4.1-2.7c0.1-2.8,6.9-7,8.5-8.3
			c0.8-2.5,3.2-7.4,3.6-9.2c0.2-0.9-0.2-4.1,0.1-5.1C50.2,14.4,50.7,8.5,50.8,1.6z"/>
	</g>
	</svg>

</p>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56026709-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>